---
- name: Check if script file exist
  stat: path={{ scriptsdir }}/{{ scriptName }}
  register: genscript_existed
  
- name: Generate rpm package by script
  shell: sh {{ scriptsdir }}/{{ scriptName }} {{ inventory_hostname }} {{ rpmdir }}
  when: genscript_existed.stat.exists == true
  
- name: List rpm package
  shell: ls {{ scriptsdir }}/{{ inventory_hostname }}_*.rpm
  register: rpm_list
  
- name: Check if rpm package genrated
  debug: msg="{{ rpm_list.stdout }}"
  failed_when: rpm_list == ''
  
