---
- name: Check if rpo generate script file exist on nodes
  stat: path={{ scriptsdir }}/{{ scriptName1 }}
  register: rpo_genscript_existed01
  when:  inventory_hostname in groups['bo2-inf-rpo']

- name: Check if ndb generate script file exist on nodes
  stat: path={{ scriptsdir }}/{{ scriptName2 }}
  register: ndb_genscript_existed02
  when:  inventory_hostname in groups['bo2-inf-ndb']
  
- name: Generate rpo rpm package by script
  shell: sh {{ scriptsdir }}/{{ scriptName1 }} {{ inventory_hostname }} {{ rpmdir }}
  when: (rpo_genscript_existed01 | length > 0) and (inventory_hostname in groups['bo2-inf-rpo'])
  
- name: Generate ndb rpm package by script
  shell: sh {{ scriptsdir }}/{{ scriptName2 }} {{ inventory_hostname }} {{ rpmdir }}
  when: (ndb_genscript_existed02 | length > 0) and (inventory_hostname in groups['bo2-inf-ndb'])
  
- name: List rpm package
  shell: ls {{ scriptsdir }}/*.rpm
  register: rpm_list
  
- name: Check if rpm package genrated
  debug: msg="{{ rpm_list.stdout }}"
  failed_when: rpm_list == ''
  
