---
- set_fact: scriptsdir="/tmp/genrpm"
      
- name: Check if script file exist
  stat: path={{ scriptsdir }}/generate_rpms.sh
  register: genscript_existed
  
- name: Generate rpm package by script
  shell: sh {{ scriptsdir }}/generate_rpms.sh {{ inventory_hostname }}
  when: genscript_existed.stat.exists == true
  
- name: Check if rpm package genrated
  stat: path={{ scriptsdir }}/{{ inventory_hostname }}_*.rpm
  register: rpm_existed
  
- name: List rpm package
  shell: ls {{ scriptsdir }}/{{ inventory_hostname }}_*.rpm
  when: rpm_existed.stat.exists == true