pipeline {
    environment {
      SCRIPT_FOLDER = "deploy-rpm"
    }	
    agent any
    stages {
        stage('Deploy RPM Package') {
        steps {
                sh "sudo ansible-playbook -i ${WORKSPACE}/${SCRIPT_FOLDER}/hosts ${WORKSPACE}/${SCRIPT_FOLDER}/site.yml"
            }
        }
		stage('Clear WORKSPACE') {
	    steps {
                sh "rm -r ${WORKSPACE}"
            }
	    }
    }
	post {

        aborted {
        
          echo "Sending message to Slack"
          slackSend (color: "${env.SLACK_COLOR_WARNING}",
                     channel: "${params.SLACK_CHANNEL_2}",
                     message: "*ABORTED:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} by ${env.USER_ID}\n More info at: ${env.BUILD_URL}")
        } // aborted
        
        failure {
        
          echo "Sending message to Slack"
          slackSend (color: "${env.SLACK_COLOR_DANGER}",
                     channel: "${params.SLACK_CHANNEL_2}",
                     message: "*FAILED:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} by ${env.USER_ID}\n More info at: ${env.BUILD_URL}")
        } // failure
        
        success {
          echo "Sending message to Slack"
          slackSend (color: "${env.SLACK_COLOR_GOOD}",
                     channel: "${params.SLACK_CHANNEL_1}",
                     message: "*SUCCESS:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} by ${env.USER_ID}\n More info at: ${env.BUILD_URL}")
        } // success

  } // post
}

