---
- hosts: localhost
  sudo: yes
  tasks:
    - name: Check if script file exist
      stat: path={{ scriptLocalPath }}/{{ scriptName }}
      register: scriptfile_existed
      failed_when: scriptfile_existed.stat.exists == false

- hosts: bo2-inf-rpo:bo2-inf-ndb
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - scripts
    - rpm